services:
  postgres:
    image: postgres:16-alpine
    container_name: refer_me_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: referme
      POSTGRES_PASSWORD: referme
      POSTGRES_DB: referme
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
